### PR TITLE
Add option that draws shadow behind artboards

### PR DESCRIPTION
**Pull request by bramchi**
Hi,

Thanks for the great Sketch plugin. It was 99% what I was looking for :-). 
I also needed the option to have shadows behind the artboards for the export. So that is what I added. And while I was at it, I also improved the name of your generated title layers. 
And then I thought, what the heck, lets make it a pull request.

The git history is a bit messy, but I hope you like the feature too.

Best regards!
Bram

### CODE REVIEW

**Comment by timothywhalin** [comment]
Great idea, Bram! I'm working on merging this with the master file as well. Yesterday I added a new "settings" menu for the plugin so you can configure the plugin within Sketch instead of editing the code. I noticed you added a new menu item "withTitlesAndShadows". I'm wondering if you think we can keep it simple with just "With Title" or "Without Titles" and you can turn on/off the shadow within Settings. Would that work for how you would want to use this?

**Comment by bramchi** [comment]
Glad you like it!
I removed that third menu option again with commit 6357105, sorry for the confusion. It was testing it on the go and found that it works better as a style setting, just like you mentioned :-) Would be great if you could expose those settings in a proper Sketch dialog!

**Comment by timothywhalin** [comment]
Just uploaded the new code with the shadow as a setting including all the values. Let me know if you want anything else added or I can close this.

**Comment by bramchi** [comment]
Great work, I like it a lot! Being able to configure those settings in a dialog is really elegant.
One tiny thing: There is a typo in the settings dialog, it says Shadow Blue Radius instead of Shadow Blur Radius.

**Pull request closed without merging**
